version: '3.8'

x-app: &app
  build:
    context: .
    target: web
  image: ghcr.io/scientist-softserv/test_app:${TAG:-latest}
  volumes:
    - .:/rails
  env_file:
    - .env
    - .env.development
  # Keep the stdin open, so we can attach to our app container's process
  # and do things such as byebug, etc:
  stdin_open: true
  # Enable sending signals (CTRL+C, CTRL+P + CTRL+Q) into the container:
  tty: true

services:
  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432
    volumes:
      - postgres:/var/lib/postgresql/data

  web:
    <<: *app
    command: bash -c "bundle exec puma -p 3000"
    ports:
      - 3000
    depends_on:
      - postgres
    environment:
      VIRTUAL_HOST: test_app.test
      VIRTUAL_PORT: 3000

  initialize_app:
    <<: *app
    entrypoint: ["sh", "-c"]
    command:
      - >
        ./bin/rails db:migrate db:seed
    depends_on:
      - web

volumes:
  postgres:
