login: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  pool: 5

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV['TEST_DB'] || 'test_app_test' %>

staging:
  <<: *default

production:
  <<: *default
